name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Type check
      run: npx tsc --noEmit || true
      continue-on-error: true
    
    - name: Run tests
      run: npm test
    
    - name: Check coverage thresholds
      run: |
        echo "Checking if coverage meets 80% threshold..."
        npm run test:coverage || {
          echo "::warning::Coverage is below 80% threshold"
          exit 0
        }